- Readme.txt
- admin/admin-interface.php
- admin/logs-viewer/tail.php
- admin/nginx-controls.php
- admin/optimize-db/optimize-db.php
- class/servebolt-nginx-fpc.class.php
- servebolt-optimizer.php
- uninstall.php
* added on/off switch for Nginx cache
* remove WP version number and generator tag
* skip concatenation of admin scripts, we use http2
* issues on Github #8 added uninstall.php + bug fixes #7 #9
* added changelog to Readme.txt
> Version 1.3

- admin/general-settings.php
- admin/views/general-settings.php
- classes/nginx-fpc/sb-nginx-fpc.php
Added basic support for Cloudflare APO
> SBWP-25 Support for Cloudflare WP APO

- classes/nginx-fpc/sb-nginx-fpc.php
Added additional cache directive to cache headers to control proxy/Nginx cache separately
> SBWP-26 Set the right browser cache and proxy cache headers

- src/Servebolt/Admin/CachePurge/CachePurge.php
Fixed (embarrasing bug) in CF option page part
> WPSO-76 Visiting the cache purging page returns error (BUG)

- servebolt-optimizer.php
- src/Servebolt/Admin/Assets.php
- src/Servebolt/CachePurge/PurgeObject/ObjectTypes/SharedMethods.php
- src/Servebolt/CachePurge/PurgeObject/PurgeObject.php
- src/Servebolt/CachePurge/WpObjectCachePurgeActions.php
- src/Servebolt/Helpers/Helpers.php
> WPSO-88 Post update doesn’t trigger purge

- src/Servebolt/AcceleratedDomains/AcceleratedDomains.php
- src/Servebolt/AssetAutoVersion/AssetAutoVersion.php
- src/Servebolt/Cli/AcceleratedDomains/AcceleratedDomains.php
- src/Servebolt/Cli/Cli.php
- src/Servebolt/DatabaseMigration/AbstractMigration.php
- src/Servebolt/DatabaseMigration/MigrationRunner.php
- src/Servebolt/DatabaseMigration/Migrations/1_QueueMigration.php
- src/Servebolt/DatabaseMigration/Migrations/2_CacheExclusionMigration.php
- src/Servebolt/DatabaseMigration/Migrations/MigrationTemplate.php
- src/Servebolt/EnvFile/Reader.php
- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/Sdk/Cloudflare/ApiMethods/CachePurge.php
- src/Servebolt/Sdk/Cloudflare/ApiMethods/User.php
- src/Servebolt/Sdk/Cloudflare/ApiMethods/Zone.php
- src/Servebolt/Sdk/Cloudflare/ApiRequestHelpers.php
- src/Servebolt/Sdk/Cloudflare/Cloudflare.php
- src/Servebolt/Sdk/Cloudflare/Exceptions/ApiError.php
- src/Servebolt/Sdk/Cloudflare/HttpClient.php
- src/Servebolt/ServeboltOptimizer.php
- src/Servebolt/SqlBuilder/SqlBuilder.php
- tests/Unit/DatabaseMigrationTest.php
- tests/Unit/QueueQueryTest.php
- tests/Unit/QueueSystemTest.php
- tests/Unit/QueueTest.php
- tests/Unit/SqlBuilderTest.php
- uninstall.php
WPSO-116 Create CLI command for disable/enable minify-feature
WPSO-115 Create CLI setup-command + enable/disable command
> WPSO-116 & WPSO-115

- src/Servebolt/Utils/EnvFile/Reader.php
Change environment reader strategy for finding home folder path to fix issue with sites running WP in subfolder
> WPSO-135 Beta 14 - Can't load environment file

- src/Servebolt/CachePurge/PurgeObject/ObjectTypes/Post.php
- src/Servebolt/CachePurge/PurgeObject/ObjectTypes/Term.php
- src/Servebolt/CachePurge/WpObjectCachePurgeActions/ContentChangeTrigger.php
- src/Servebolt/CachePurge/WpObjectCachePurgeActions/SlugChangeTrigger.php
- src/Servebolt/Compatibility/WooCommerce/ProductCachePurgeOnStockChange.php
- src/Servebolt/Compatibility/WooCommerce/ProductVariationCachePurge.php
- src/Servebolt/Compatibility/WooCommerce/WooCommerce.php
- src/Servebolt/FullPageCache/FullPageCache.php
- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/ServeboltOptimizer.php
- src/Servebolt/Utils/Crypto/OptionEncryption.php
Added events for purging product cache whenever stock is updated
> WPSO-137 Purge product on stock status change

- src/Servebolt/CachePurge/PurgeObject/ObjectTypes/Post.php
- src/Servebolt/CachePurge/PurgeObject/ObjectTypes/Term.php
- src/Servebolt/CachePurge/WpObjectCachePurgeActions/ContentChangeTrigger.php
- src/Servebolt/CachePurge/WpObjectCachePurgeActions/SlugChangeTrigger.php
- src/Servebolt/Compatibility/WooCommerce/ProductCachePurgeOnStockChange.php
- src/Servebolt/Compatibility/WooCommerce/ProductVariationCachePurge.php
- src/Servebolt/Compatibility/WooCommerce/WooCommerce.php
- src/Servebolt/FullPageCache/FullPageCache.php
- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/ServeboltOptimizer.php
- src/Servebolt/Utils/Crypto/OptionEncryption.php
Need to use the compatibility-namespace in WPSO-134, hence the merge from WPSO-137.
> Merged WPSO-137 to use compatibility-namespace

- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/PluginActiveStateHandling.php
- src/Servebolt/ServeboltOptimizer.php
Added class that handles plugin activation/deactivation
> WPSO-155 Create plugin activation/deactivation class

- src/Servebolt/Admin/AcceleratedDomainsControl/AcceleratedDomainsControl.php
- src/Servebolt/Compatibility/WpRocket/WpRocket.php
Added event when ACD is activated/deactivated
> WPSO-134 Create ACD activation event

- src/Servebolt/AcceleratedDomains/AcceleratedDomains.php
- src/Servebolt/Admin/AcceleratedDomainsControl/AcceleratedDomainsControl.php
Moved ACD active state event from ACD GUI-class to ACD-class where it belongs
> WPSO-157 Create ACD activation event - Moved ACD active state event handling

- src/Servebolt/Admin/Assets.php
Fixed typo in JS file URL, added wrapper methods for script and style enqueue.
> WPSO-169 Beta18 - PHP warning when editing or adding a new post in WP-backend

- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/Sdk/Cloudflare/HttpClient.php
- src/Servebolt/Utils/DatabaseMigration/MigrationRunner.php
- tests/Unit/HelpersTest.php
- tests/Unit/PluginInitTest.php
Added user agent to WP-based CF SDK, added tests for constants and plugin version number
> WPSO-74 Set "ServeboltOptimizer/version" User Agent instead of "GuzzleHTTP/7"

- src/Servebolt/Admin/AdminGuiController.php
- src/Servebolt/Admin/CloudflareImageResize/CloudflareImageResize.php
- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/PluginActiveStateHandling.php
- src/Servebolt/PluginActiveStateHandling/PluginActiveStateHandling.php
- src/Servebolt/PluginActiveStateHandling/SingleSitePluginActivationConstraint.php
- src/Servebolt/ServeboltOptimizer.php
- uninstall.php
Minor refactor, added prevention of plugin activation on a single site when running in a multisite
> WPSO-18 Make the plugin impossible to enable on a single site in a multisite

- src/Servebolt/CachePurge/PurgeObject/ObjectTypes/Post.php
- src/Servebolt/CachePurge/WordPressCachePurge/SharedMethods.php
- src/Servebolt/Compatibility/WooCommerce/ProductVariationCachePurge.php
- src/Servebolt/Views/cache-settings/cache-purge/configuration/cron-configuration.php
- Minor cleaup
- Corrected typo in cache purge URL-related filter
- Fixed issue with WooCommerce variable product during cache purge
> WPSO-189 Beta24 - Fatal error when updating product 

- src/Servebolt/Views/dashboard/dashboard-multisite-sub-site.php
- src/Servebolt/Views/dashboard/dashboard-multisite-super-admin.php
- src/Servebolt/Views/dashboard/dashboard-single-site.php
- src/Servebolt/Views/log-viewer/log-viewer.php
- Adjusted warning when log file does not exists
- Added missing link to ACD on dashboard
- Updated plugin dashboard links (so they correlate with the order in the sidebar menu, change text)
> WPSO-194 Missing Accelerated Domains link on plugin landing page

- src/Servebolt/Admin/CachePurgeControl/CachePurgeControl.php
- src/Servebolt/Admin/FullPageCacheControl/FullPageCacheControl.php
- src/Servebolt/Admin/PerformanceChecks/PerformanceChecks.php
- src/Servebolt/Helpers/Helpers.php
Fixed bug with script enqueue for performance optimizer page, added helper function to ease the process of current screen checking
> WPSO-227 Beta25 - "Run the optimizer" Not working for multisite

- Readme.txt
- servebolt-optimizer.php
> WPSO-244 Update version all over

- src/Servebolt/FullPageCache/FullPageCacheHeaders.php
Changed the order of the cache conditions so that the cache exception works
> WPSO-256 Wrong headers for posts on exclusion list

- src/Servebolt/Admin/Assets.php
- src/Servebolt/Admin/CachePurgeControl/CachePurgeControl.php
- src/Servebolt/Admin/FullPageCacheControl/FullPageCacheControl.php
- src/Servebolt/Admin/PerformanceChecks/PerformanceChecks.php
- src/Servebolt/Helpers/Helpers.php
- tests/Unit/WpAssetTest.php
Originating from this PR: https://github.com/Servebolt/servebolt-optimizer/pull/214
> WPSO-268 Replace filemtime for static assets

- README.md
- Readme.txt
Added changelog-entry for v3.0.1
> WPSO-269 Add changelog-entry for v3.0.1

- Readme.txt
- servebolt-optimizer.php
> WPSO-270 Update version number to v3.0.1

- src/Servebolt/AcceleratedDomains/AcceleratedDomains.php
- src/Servebolt/AcceleratedDomains/ImageResize/AcceleratedDomainsImageResize.php
- src/Servebolt/AcceleratedDomains/ImageResize/ImageResize.php
- src/Servebolt/Admin/AcceleratedDomainsImageResizeControl/AcceleratedDomainsImageResizeControl.php
- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/ServeboltOptimizer.php
- src/Servebolt/Views/accelerated-domains/image-resize/image-resize.php
- src/Servebolt/Views/accelerated-domains/image-resize/settings-form.php
- tests/Unit/HelpersTest.php
Added helper functions for overriding and adding default option values + tests, completed ACD Image Resize GUI with option selector
> WPSO-238 + WPSO-242

- src/Servebolt/AcceleratedDomains/ImageResize/AcceleratedDomainsImageResize.php
- src/Servebolt/AcceleratedDomains/ImageResize/ImageResize.php
- src/Servebolt/Cli/AcceleratedDomains/AcceleratedDomains.php
- src/Servebolt/CloudflareImageResize/CloudflareImageResize.php
Added CLI commands to toggle ACD image resize feature on/off
> WPSO-281 Add CLI-command - on/off

- src/Servebolt/AcceleratedDomains/ImageResize/AcceleratedDomainsImageResize.php
- src/Servebolt/AcceleratedDomains/ImageResize/ImageResize.php
- src/Servebolt/Admin/AcceleratedDomainsImageResizeControl/AcceleratedDomainsImageResizeControl.php
- src/Servebolt/Views/accelerated-domains/image-resize/settings-form.php
Added half sizes of the existing sizes in the srcset-attribute
> WPSO-279 Add half-sizes to the srcset-array

- src/Servebolt/AcceleratedDomains/ImageResize/ImageSizeIndexModel.php
- src/Servebolt/Cli/AcceleratedDomains/AcceleratedDomains.php
- src/Servebolt/Cli/AcceleratedDomains/AcceleratedDomainsImageResize.php
- src/Servebolt/Cli/AcceleratedDomains/AcceleratedDomainsImageSizeIndex.php
- tests/Unit/AcceleratedDomainsImageSizeIndexTest.php
- Added tests for exist-check with ACD image size index
- Moved ACD image resize commands to own file
- Finished ACD image size index CLI commands with validation
- Changed methods of class ImageSizeIndexModel to static
> WPSO-286 Add CLI-command - image size index

- src/Servebolt/AcceleratedDomains/ImageResize/AcceleratedDomainsImageResize.php
- src/Servebolt/AcceleratedDomains/ImageResize/ImageSizeIndexModel.php
- src/Servebolt/AcceleratedDomains/ImageResize/WpImageIndex.php
Added the custom sizes to the srcset-array
> WPSO-292 Apply sizes from index to srcset-array

- assets/src/js/acd-image-size-index.js
- src/Servebolt/Views/accelerated-domains/image-resize/settings-form.php
Made ACD image options fields show/hide based on whether the feature is active or not
> WPSO-293 Hide form elements when feature is not active

- php-outdated.php
- servebolt-optimizer.php
- src/Servebolt/Helpers/Helpers.php
Added conditional-error messages for sites running on old PHP versions
> WPSO-258 "Disable" the plugin on <PHP 7.3

- src/Servebolt/AcceleratedDomains/ImageResize/ImageResize.php
- tests/Unit/AcceleratedDomainsImageResize/AcceleratedDomainsImageResizeTest.php
- WPSO-297 Prevent default image quality parameter from being sent unless it has a different value
> WPSO-172 Accelerated Domains Image Resizing

- src/Servebolt/AcceleratedDomains/AcceleratedDomainsHeaders.php
Removed s-maxage from header 'CDN-Cache-Control'
> WPSO-240 Implement CDN TTL header support

- src/Servebolt/Compatibility/WpRocket/DisableWpRocketCache.php
Added additional filters to disabled WP Rocket cache feature
> WPSO-214 Make disabling WP Rocket's components more complete

- assets/src/js/acd-image-size-index.js
- src/Servebolt/Views/accelerated-domains/image-resize/image-resize.php
- src/Servebolt/Views/accelerated-domains/image-resize/promo.php
- src/Servebolt/Views/accelerated-domains/image-resize/settings-form.php
- src/Servebolt/Views/accelerated-domains/tabs-menu.php
- tests/Unit/AcceleratedDomainsImageResize/AcceleratedDomainsImageResizeTest.php
- tests/Unit/HelpersTest.php
@roberts91 please check that I used getServeboltAdminUrl() correctly in promo.php
> updated strings and made strings translation ready

- src/Servebolt/Prefetching/ManifestFileWriter.php
- tests/Unit/Prefetch/ManifestFileWriterTest.php
Changed manifest file writer to write to multiple files instead of just one
> WPSO-308 Create different files for different prefetch types (menu, script, style)

- src/Servebolt/Prefetching/ManifestFileWriter.php
- tests/Unit/Prefetch/ManifestFileWriterTest.php
Added optional limit to max number of lines in manifest files
> WPSO-309 Create a filter for max limit of lines per file

- src/Servebolt/AcceleratedDomains/ImageResize/ImageResize.php
- tests/Unit/AcceleratedDomainsImageResize/AcceleratedDomainsImageResizeTest.php
Ensured that src-tag is correct on images
> WPSO-300 Deliver original image in src tag on responsive images

- src/Servebolt/Prefetching/ManifestDataModel.php
- src/Servebolt/Prefetching/ManifestFileWriter.php
- src/Servebolt/Prefetching/ManifestFilesModel.php
- src/Servebolt/Prefetching/ManifestHeaders.php
- src/Servebolt/Prefetching/Prefetching.php
- src/Servebolt/Prefetching/WpPrefetching.php
- tests/Unit/Prefetch/ManifestFileWriterTest.php
Added manifest files to header-feature, added model to store which files we wrote to disk so that we don't need to check on disk during page load, added tests
> WPSO-307 Add manifest file to header

- src/Servebolt/Helpers/Helpers.php
Added more options for when deleting options when deleting the plugin
> WPSO-312 Image sizes not cleaned on plugin delete

- assets/src/js/prefetching.js
- src/Servebolt/Admin/AdminGuiController.php
- src/Servebolt/Admin/PrefetchingControl/PrefetchingControl.php
- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/Prefetching/ManifestFileWriter.php
- src/Servebolt/Prefetching/WpPrefetching.php
- src/Servebolt/ServeboltOptimizer.php
- src/Servebolt/Views/accelerated-domains/image-resize/settings-form.php
- src/Servebolt/Views/prefetching/network-list-view.php
- src/Servebolt/Views/prefetching/prefetching.php
- src/Servebolt/Views/prefetching/settings-form.php
Added configuration GUI for prefetching-feature
> WPSO-3030 Add configuration GUI

- README.md
- Readme.txt
- php-outdated.php
- src/Servebolt/Admin/AcceleratedDomainsImageControl/Ajax/ImageSizeIndex.php
- src/Servebolt/Admin/AdminGuiController.php
- src/Servebolt/Admin/CachePurgeControl/Ajax/PurgeActions.php
- src/Servebolt/Cli/AcceleratedDomains/AcceleratedDomainsImageResize.php
- src/Servebolt/Cli/AcceleratedDomains/AcceleratedDomainsImageSizeIndex.php
- src/Servebolt/Cli/Cache/CfSetup.php
- src/Servebolt/Cli/Cache/PurgeActions.php
- src/Servebolt/Cli/CloudflareImageResize/CloudflareImageResize.php
- src/Servebolt/Cli/Fpc/Fpc.php
- src/Servebolt/Cli/General/General.php
- src/Servebolt/DatabaseOptimizer/DatabaseOptimizer.php
- src/Servebolt/Views/accelerated-domains/acd-promo.php
Various spelling, consistency and grammar updates are fixed in this PR. As well as an updated Readme.txt changelog entry for 3.1
> v3.1 Textual updates

- src/Servebolt/Prefetching/ManifestFileWriter.php
- tests/Unit/Prefetch/ManifestFileWriterTest.php
Updated folder path for manifest files + updated tests
> WPSO-314 Change folder name for manifest files

- assets/src/js/prefetching.js
- src/Servebolt/Admin/PrefetchingControl/Ajax/PrefetchingFileGeneration.php
- src/Servebolt/Admin/PrefetchingControl/PrefetchingControl.php
- src/Servebolt/Prefetching/Prefetching.php
- src/Servebolt/Views/prefetching/settings-form.php
Added feature to regenerate manifest files, fixed issue with change event for manifest file max number of lines options field
> WPSO-315 Add manual prefetch button

- servebolt-optimizer.php
> WPSO-253 Create a constant for Accelerated Domains version

- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/MenuCache/MenuCache.php
- src/Servebolt/MenuCache/WpMenuCache.php
- src/Servebolt/ServeboltOptimizer.php
- tests/Unit/WpMenuCacheTest.php
> WPSO-322 Write tests

- src/Servebolt/Admin/FullPageCacheControl/Ajax/FpcPostExclusion.php
- src/Servebolt/Admin/FullPageCacheControl/FullPageCacheControl.php
- src/Servebolt/CachePurge/WordPressCachePurge/PostMethods.php
- src/Servebolt/FullPageCache/FullPageCache.php
- src/Servebolt/Utils/Queue/Queue.php
- tests/Unit/FullPageCacheTest.php
Added actions to react to posts being added/removed from FPC exclusion list, added test scaffolding
> WPSO-224 Cache needs to be cleared for posts added to the FPC exclude list

- src/Servebolt/Admin/PerformanceOptimizer/PerformanceOptimizerAdvanced.php
- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/ServeboltOptimizer.php
- src/Servebolt/TextDomainLoader/TextDomainLoader.php
- src/Servebolt/TextDomainLoader/WpTextDomainLoader.php
- src/Servebolt/Views/performance-optimizer/advanced/settings-form.php
Added PoC and rewrite it to fit our standards
> WPSO-274 Translations speed up

- src/Servebolt/CachePurge/WpObjectCachePurgeActions/AttachmentUpdateTrigger.php
- src/Servebolt/CachePurge/WpObjectCachePurgeActions/ContentChangeTrigger.php
- src/Servebolt/CachePurge/WpObjectCachePurgeActions/DeletionCacheTrigger.php
- src/Servebolt/CachePurge/WpObjectCachePurgeActions/SlugChangeTrigger.php
- src/Servebolt/CachePurge/WpObjectCachePurgeActions/WpObjectCachePurgeActions.php
- src/Servebolt/Traits/EventToggler.php
- tests/Unit/CachePurgeTriggerTest.php
- Added test for the image editor automatic cache purge for images
- Added trait to easier reload/add/remove cache purge events
> WPSO-338 Create tests

- src/Servebolt/Admin/AdminGuiController.php
- src/Servebolt/Admin/FullPageCacheControl/CacheTtlControl.php
- src/Servebolt/Views/cache-settings/cache-ttl/cache-ttl.php
- src/Servebolt/Views/cache-settings/cache-ttl/network-list-view.php
- src/Servebolt/Views/cache-settings/cache-ttl/settings-form.php
- src/Servebolt/Views/cache-settings/tabs-menu.php
Added new cache settings tab - 'Cache TTL'
> WPSO-342 Create new tab

- assets/src/js/acd-image-size-index.js
- assets/src/js/cache-ttl.js
- assets/src/js/general-vanilla.js
- assets/src/js/prefetching.js
- src/Servebolt/Admin/Assets.php
- src/Servebolt/Admin/FullPageCacheControl/CacheTtlControl.php
- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/Views/accelerated-domains/image-resize/settings-form.php
- src/Servebolt/Views/cache-settings/cache-ttl/cache-ttl.php
- src/Servebolt/Views/cache-settings/cache-ttl/settings-form.php
- src/Servebolt/Views/performance-optimizer/prefetching/settings-form.php
Added working table form (WPSO-343, WPSO-344, WPSO-346 done)
> WPSO-343 Create table scaffoling

- src/Servebolt/Admin/AdminBarGui/Nodes/2_CachePurgeNode.php
- src/Servebolt/Admin/CachePurgeControl/Ajax/PurgeActions.php
- src/Servebolt/Admin/CachePurgeControl/CachePurgeControl.php
- src/Servebolt/Admin/CachePurgeControl/CachePurgeRowActions.php
Moved cache purge row actions to own class + added checks if the feature is available and that the user has sufficient capabilities
> WPSO-355 Add capability checks to row actions

- Readme.txt
- servebolt-optimizer.php
- src/Servebolt/Admin/AdminGuiController.php
- src/Servebolt/Admin/PerformanceOptimizer/PerformanceOptimizer.php
- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/Views/performance-optimizer/tabs-menu.php
Updated version numbers, temporarily disabled the prefetching-feature
> WPSO-358 Temporarily disable the prefetch-feature

- src/Servebolt/AcceleratedDomains/AcceleratedDomainsHeaders.php
- src/Servebolt/FullPageCache/FullPageCacheHeaders.php
Moved custom cache TTL from FPC-class to ACD cache headers only
> WPSO-361 Custom cache time for Accelerated Domains and CF only

- src/Servebolt/Admin/CachePurgeControl/Ajax/PurgeActions.php
- src/Servebolt/Queue/Queues/UrlQueue.php
- src/Servebolt/Queue/Queues/WpObjectQueue.php
- src/Servebolt/Utils/Queue/Queue.php
> WPSO-341 Accumulation of rows in queue table

- assets/src/js/acd-control.js
- assets/src/js/cache-purge-trigger.js
- assets/src/js/general-vanilla.js
- src/Servebolt/Admin/AcceleratedDomainsControl/AcceleratedDomainsControl.php
- src/Servebolt/Admin/AcceleratedDomainsControl/Ajax/PurgeActions.php
- src/Servebolt/Admin/CachePurgeControl/Ajax/PurgeActions.php
- src/Servebolt/CachePurge/CachePurge.php
- src/Servebolt/Views/accelerated-domains/control/settings-form.php
WIP - Added purge all button to acd config form + AJAX handling
> WPSO-285 Add purge all-button to the ACD settings form

- assets/src/js/acd-control.js
- assets/src/js/cache-purge-trigger.js
- assets/src/js/general-vanilla.js
- src/Servebolt/Admin/AcceleratedDomainsControl/AcceleratedDomainsControl.php
- src/Servebolt/Admin/AcceleratedDomainsControl/Ajax/PurgeActions.php
- src/Servebolt/Admin/CachePurgeControl/Ajax/PurgeActions.php
- src/Servebolt/CachePurge/CachePurge.php
- src/Servebolt/Views/accelerated-domains/control/settings-form.php
- WPSO-285 Add purge all-button to the ACD settings form
> WPSO-219 Beta25 - purging acd cache won't work when acd is deactivated

- src/Servebolt/AcceleratedDomains/AcceleratedDomainsHeaders.php
- src/Servebolt/Admin/AdminGuiController.php
- src/Servebolt/Compatibility/Cloudflare/Apo.php
- src/Servebolt/FullPageCache/FullPageCache.php
- src/Servebolt/Views/cache-settings/cache-purge/cache-purge.php
- src/Servebolt/Views/cache-settings/cache-purge/configuration/configuration.php
- src/Servebolt/Views/cache-settings/cache-ttl/cache-ttl.php
- src/Servebolt/Views/cache-settings/cache-ttl/settings-form.php
- src/Servebolt/Views/cache-settings/tabs-menu.php
- src/Servebolt/Views/general/tabs.php
Updated strings for custom cache TTL, minor tweaks, disabled custom cache TTL for non Servebolt-users and whenever ACD is disabled
> WPSO-222 Cache time per post type and taxonomy

- src/Servebolt/Compatibility/Jetpack/DisableSiteAcceleratorOnAcd.php
Added missing module for Jetpack compatiblity fix
> WPSO-369 ACD and ACD Image Resizing doesn't completely turn of Jetpack's Site Accelerator 

- src/Servebolt/Cli/Cache/CacheSettingsConstraints.php
- src/Servebolt/Helpers/Helpers.php
- tests/Unit/HelpersTest.php
Fixed fatal error due to missing import of class/namespace
> WPSO-373 wp servebolt cache settings list throws a fatal error

- src/Servebolt/Cli/Cache/CacheSettingsConstraints.php
> WPSO-377 wp servebolt cache settings list fatal error

- README.md
- Readme.txt
- servebolt-optimizer.php
- src/Servebolt/MenuCache/MenuCache.php
- src/Servebolt/MenuCache/MenuCachePurge.php
- src/Servebolt/MenuCache/SharedMethods.php
- src/Servebolt/MenuCache/WpMenuCache.php
Turns out this was not on us, but a bug in another plugin propagating throughout WordPress. But we learned a thing or two and did some improvements regardless.
> WPSO-400 SBO 3.2 - MenuCache Bug

- src/Servebolt/Admin/AdminBarGui/AdminBarGui.php
- src/Servebolt/Admin/AdminBarGui/Nodes/1_ServeboltControlPanelNode.php
- src/Servebolt/Admin/AdminBarGui/Nodes/2_CachePurgeNodes.php
- src/Servebolt/Admin/AdminBarGui/Nodes/3_SettingsNode.php
Cleaned up markup in WP nav bar
> WPSO-406 SBO 3.2 - HTML markup error

- src/Servebolt/CachePurge/WpObjectCachePurgeActions/DeletionCacheTrigger.php
Removed type hint for a more graceful fail
> WPSO-408 SBO 3.2 - taxonomy and deactivate plugin bug

- src/Servebolt/Admin/CachePurgeControl/Ajax/PurgeActions.php
- src/Servebolt/Compatibility/WooCommerce/ProductCachePurgeOnStockChange.php
- Fixed bug in WooCommerce stock change cache purge
- Added immediate purge as default when purging cache on WooCommerce stock change
- Cleaned up purge action AJAX setup after merge with v3.3-branch
> WPSO-207 The cache should be purged immediately on WooCommerce product stock amount/status change

- src/Servebolt/Admin/CachePurgeControl/Ajax/Configuration.php
Fixed issue with faulty checkbox-check during CF cache purge configuration form submit
> WPSO-409 Cache purge settings form - CF validation not working

- languages/servebolt-optimizer.pot
- src/Servebolt/Admin/AcceleratedDomainsImageControl/AcceleratedDomainsImageResizeControl.php
- src/Servebolt/Admin/AdminGuiController.php
- src/Servebolt/Admin/CachePurgeControl/CachePurgeControl.php
- src/Servebolt/Admin/PerformanceOptimizer/MenuCacheControl.php
- src/Servebolt/Admin/Prefetching/PrefetchingControl.php
- src/Servebolt/Views/accelerated-domains/image-resize/image-size-index.php
- src/Servebolt/Views/cache-settings/cache-purge/configuration/acd-configuration.php
- src/Servebolt/Views/cache-settings/cache-purge/configuration/cloudflare-configuration.php
- src/Servebolt/Views/cache-settings/cache-purge/queue/list.php
- src/Servebolt/Views/cache-settings/cache-settings/network-list-view.php
- src/Servebolt/Views/cache-settings/cache-settings/settings-form.php
- src/Servebolt/Views/cache-settings/tabs-menu.php
- src/Servebolt/Views/dashboard/dashboard-multisite-sub-site.php
- src/Servebolt/Views/dashboard/dashboard-multisite-super-admin.php
- src/Servebolt/Views/dashboard/dashboard-single-site.php
- src/Servebolt/Views/dashboard/dashboard.php
- src/Servebolt/Views/general-settings/general-settings.php
- src/Servebolt/Views/log-viewer/log-viewer.php
Added missing translations, updated POT-file, changed capitalization in some strings
> WPSO-411 Capitalize words

- src/Servebolt/AssetAutoVersion/AssetAutoVersion.php
- src/Servebolt/CachePurge/WpObjectCachePurgeActions/AttachmentUpdateTrigger.php
- src/Servebolt/CachePurge/WpObjectCachePurgeActions/DeletionCacheTrigger.php
- src/Servebolt/DatabaseOptimizer/DatabaseOptimizer.php
- src/Servebolt/FullPageCache/FullPageCache.php
- src/Servebolt/Utils/Crypto/Crypto.php
- src/Servebolt/Utils/EnvFile/Reader.php
- Added missing exception namespace inclusions
> WPSO-413 Ensure that we have try-catch statements around API calls

- src/Servebolt/CronControl/MultisiteCronInstaller/MultisiteCronInstaller.php
- src/Servebolt/CronControl/MultisiteCronInstaller/ScriptTemplate.php
- tests/Unit/CronControlTest.php
Added script installation class + test
> WPSO-431 Create multisite cron script installer

- composer.lock
- src/Servebolt/Cli/Cli.php
- src/Servebolt/Cli/CronControl/CronControl.php
- src/Servebolt/CronControl/CronControl.php
- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/ServeboltOptimizer.php
- src/Servebolt/Utils/WPConfigTransformer.php
- tests/Unit/AcceleratedDomainsImageResize/AcceleratedDomainsImageResizeTest.php
- tests/Unit/CronControl/CronControlTest.php
- tests/Unit/CronControl/wp-config-sample.php
- Added CLI command to control the WP Cron,
- Added helper class to manipulate the wp-config.php-file without the WP CLI
> WPSO-425 Create CLI command for WP cron disabling

- src/Servebolt/Cli/CronControl/CronControl.php
- src/Servebolt/Cli/CronControl/CronStatus.php
- src/Servebolt/CronControl/CronControl.php
- src/Servebolt/CronControl/MultisiteCronInstaller/MultisiteCronInstaller.php
- src/Servebolt/CronControl/WpCronControl.php
- tests/Unit/CronControl/CronControlTest.php
Added WP cron status cli command + tests
> WPSO-427 Create CLI command

- src/Servebolt/Admin/AdminGuiController.php
- src/Servebolt/Admin/PerformanceOptimizer/PerformanceOptimizer.php
- src/Servebolt/Admin/PerformanceOptimizer/PerformanceOptimizerAdvanced.php
- src/Servebolt/Admin/PerformanceOptimizer/SiteOptionsHandling.php
- src/Servebolt/Compatibility/ActionScheduler/DisableActionSchedulerDefaultRunner.php
- src/Servebolt/CronControl/ActionSchedulerUnixCronControl.php
- src/Servebolt/CronControl/UnixCronControl.php
- src/Servebolt/CronControl/WpCronControl.php
- src/Servebolt/CronControl/WpUnixCronControl.php
- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/Views/performance-optimizer/advanced/advanced.php
- src/Servebolt/Views/performance-optimizer/advanced/network-list-view.php
- src/Servebolt/Views/performance-optimizer/advanced/network-settings-form.php
- src/Servebolt/Views/performance-optimizer/advanced/settings-form.php
- src/Servebolt/Views/performance-optimizer/advanced/shared-settings/action-scheduler.php
- src/Servebolt/Views/performance-optimizer/performance-optimizer.php
- tests/Unit/HelpersTest.php
- uninstall.php
- Various cleaup
- WPSO-461 Site options must be delete on uninstall
- WPSO-457 Create a GUI for controlling the feature
- WPSO-462 Add multisite-support to Advanced-tag in Performance Optimizer options page,
- Added helper function to listen for updates in site option
- Added helper function to help listen for updates in option (not only changes)
- WPSO-459 Update the 'Suggested optimizations' for WP Cron setup
> WPSO-457 Create a GUI for controlling the feature

- src/Servebolt/Admin/PerformanceOptimizer/PerformanceOptimizerAdvanced.php
- src/Servebolt/Admin/PerformanceOptimizer/SiteOptionsHandling.php
- src/Servebolt/CronControl/ActionSchedulerCronControl.php
- src/Servebolt/CronControl/ActionSchedulerUnixCronControl.php
- src/Servebolt/CronControl/UnixCronControl.php
- src/Servebolt/CronControl/WpCronControl.php
- src/Servebolt/CronControl/WpUnixCronControl.php
- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/Views/performance-optimizer/advanced/network-list-view.php
- src/Servebolt/Views/performance-optimizer/advanced/network-settings-form.php
- src/Servebolt/Views/performance-optimizer/advanced/settings-form.php
- src/Servebolt/Views/performance-optimizer/advanced/shared-settings/action-scheduler.php
- src/Servebolt/Views/performance-optimizer/advanced/shared-settings/wp-cron.php
- Added GUI for controlling the WP UNIX Cron feature
- Added script deletion when activating Action Scheduler/WP Cron feature on a single site
- Added command removal of other Action Scheduler/WP Cron when setting up the cronjob command
> WPSO-463 Create GUI to control feature

- src/Servebolt/MenuOptimizer/MenuOptimizer.php
Added extra checks to prevent menu cache from failing
> WPSO-471 Menu optimizer - Fatal error

- src/Servebolt/AcceleratedDomains/ImageResize/FeatureAccess.php
- src/Servebolt/Admin/AcceleratedDomainsImageControl/AcceleratedDomainsImageSizeIndexControl.php
- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/Utils/EnvironmentConfig.php
- tests/Unit/AcceleratedDomainsImageResize/AcceleratedDomainsImageResizeTest.php
- tests/Unit/EnvironmentConfigTest.php
- tests/Unit/HelpersTest.php
- Added environment config reader with cache feature
- Added method to check access to Accelerated Domains Image Resize-feature
> WPSO-467 Servebolt Optimizer must access the environment config for current site (Servebolt clients only)

- src/Servebolt/AcceleratedDomains/AcceleratedDomains.php
- src/Servebolt/AcceleratedDomains/ImageResize/AcceleratedDomainsImageResize.php
- src/Servebolt/Views/accelerated-domains/image-resize/image-resize.php
Added feature access to check to Accelerated Domains Image Resize-feature
> WPSO-475 Use access check in settings GUI

- src/Servebolt/MenuOptimizer/SharedMethods.php
Changed menu signature cache key
> WPSO-464 Report of small issue with menu cache

- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/Utils/EnvironmentConfig.php
- tests/Unit/AcceleratedDomainsImageResize/AcceleratedDomainsImageResizeTest.php
- tests/Unit/EnvironmentConfigTest.php
Added function to check whether request happens using Accelerated Domains + updated tests
> WPSO-476 Ensure to only query environment config where config is present

- src/Servebolt/Prefetching/FilePurge.php
- src/Servebolt/Prefetching/Prefetching.php
- src/Servebolt/Prefetching/WpPrefetching.php
- Added manifest file cache purge on menu update (WPSO-417) and theme switch (WPSO-479)
> WPSO-417 Purge menu manifest cache on menu update

- src/Servebolt/Cli/HtmlCache/HtmlCache.php
Fixed minor error in CLI for controlling HTML cache post exclusion
> WPSO-487 PHP Error in CLI context when interacting with post exclusion from HTML cache

- assets/src/js/cache-purge.js
- src/Servebolt/Admin/AdminBarGui/Nodes/2_CachePurgeNodes.php
- src/Servebolt/Admin/CachePurgeControl/Ajax/PurgeActions.php
- src/Servebolt/Admin/CachePurgeControl/CachePurgeControl.php
- src/Servebolt/CachePurge/CachePurge.php
- src/Servebolt/Views/cache-settings/cache-purge/configuration/cache-purge-triggers.php
- src/Servebolt/Views/cache-settings/cache-purge/configuration/configuration.php
Added Servebolt CDN as a cache provider, added conditional check for current driver trait to check for URL cache purge support
> WPSO-496 Create cache provider for Servebolt CDN

- src/Servebolt/CachePurge/WpObjectCachePurgeActions/WpObjectCachePurgeActions.php
Disabled automatic cache purging if Servebolt CDN-driver is selected
> WPSO-498 Disable automatic cache purge for Servebolt CDN cache provider

- src/Servebolt/AcceleratedDomains/Prefetching/FilePurge.php
- src/Servebolt/AcceleratedDomains/Prefetching/ManifestDataModel.php
- src/Servebolt/AcceleratedDomains/Prefetching/ManifestFileWriter.php
- src/Servebolt/AcceleratedDomains/Prefetching/ManifestFilesModel.php
- src/Servebolt/AcceleratedDomains/Prefetching/ManifestHeaders.php
- src/Servebolt/AcceleratedDomains/Prefetching/Prefetching.php
- src/Servebolt/AcceleratedDomains/Prefetching/WpPrefetching.php
- src/Servebolt/Admin/Prefetching/Ajax/PrefetchingFileGeneration.php
- src/Servebolt/Admin/Prefetching/PrefetchingControl.php
- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/ServeboltOptimizer.php
- src/Servebolt/Views/accelerated-domains/prefetching/network-list-view.php
- tests/Unit/Prefetch/ManifestFileWriterTest.php
Fixed bug where prefetching-cache was not purged when a new page was created and was automatically added to a menu
> WPSO-502 Prefetching not working

- src/Servebolt/CronControl/UnixCronModel.php
Changed cron default notification setting
> WPSO-504 5. Cron setup

- src/Servebolt/Cli/General/General.php
- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/MenuOptimizer/WpMenuOptimizer.php
- src/Servebolt/ServeboltOptimizer.php
- src/Servebolt/Utils/DatabaseMigration/MigrationRunner.php
- src/Servebolt/Utils/DatabaseMigration/Migrations/4_LegacyTransientCleaner.php
- src/Servebolt/Utils/DatabaseMigration/Migrations/MigrationTemplate.php
- src/Servebolt/Utils/PostUpgradeActions.php
- src/Servebolt/WpDatabaseMigrations.php
- tests/Unit/DatabaseMigrationTest.php
- tests/Unit/HelpersTest.php
- tests/Unit/QueueQueryTest.php
- tests/Unit/SqlBuilderTest.php
- Code refactor
- Fixed bug in database migration utility
- Added legacy transient cleaner-migration
> WPSO-530 Create cleanup migration to clean retrospective (legacy) transients

- src/Servebolt/AcceleratedDomains/Prefetching/ManifestFileWriter.php
Added more checks to prefetch-folder cleanup method
> WPSO-526 Generate prefetch manifest file immediately fails

- src/Servebolt/CronControl/UnixCronModel.php
Changed cron API property from 'enabled' to 'active' according to updated API schema
> WPSO-532 Update Cron model to fit with updated API schema

- src/Servebolt/Admin/AdminBarGui/Nodes/1_ServeboltControlPanelNode.php
- src/Servebolt/Admin/CachePurgeControl/CachePurgeControl.php
- src/Servebolt/Admin/PerformanceOptimizer/PerformanceOptimizer.php
- src/Servebolt/Admin/PerformanceOptimizer/PerformanceOptimizerAdvanced.php
- src/Servebolt/CachePurge/CachePurge.php
- src/Servebolt/CachePurge/WordPressCachePurge/WordPressCachePurge.php
- src/Servebolt/Compatibility/WooCommerce/ProductCachePurgeOnStockChange.php
- src/Servebolt/Helpers/Helpers.php
- src/Servebolt/ServeboltOptimizer.php
- src/Servebolt/Utils/EnvFile/Reader.php
- src/Servebolt/Views/cache-settings/cache-purge/configuration/configuration.php
- tests/Unit/FullPageCacheTest.php
- tests/Unit/HelpersTest.php
- tests/Unit/Traits/EnvFile/EnvFileReaderTrait.php
Added better handling for which driver can be selected
> WPSO-534 External bug: Errors in query monitor

- src/Servebolt/Views/performance-optimizer/menu-optimizer/settings-form.php
Added help-texts + changed labels for the menu optimizer-feature
> WPSO-518 Github Issue #399 - Ambiguous wording in Menu Optimizer settings

- languages/servebolt-optimizer.pot
- package.json
- src/Servebolt/CronControl/UnixCronControl.php
- src/Servebolt/CronControl/UnixCronModel.php
- yarn.lock
- Updated POT-file
- Updated NPM dependencies
- Fixed issue in cron interaction for disabled entries
> WPSO-554 Previous cron entries not deleted if not active
