classes/cloudflare-image-resize/cloudflare-image-resizing.php

The Cloudflare Image Resize feature was not working due to invalid arguments in the URL.

Fixed error in CF image resize URLs

---

admin/general-settings.php
cli/classes/general-settings-extra.class.php
cli/classes/general-settings.class.php
servebolt-optimizer.php

The list-command did not return the values, only the list of available settings. It now returns values as well as having multisite support. Also fixed a bug related to the way boolean values where handled and displayed.

Bugfix in settings system

---

src/Servebolt/Admin/AdminGuiController.php

Fixed error where Error log GUI was not shown (due to improper initiaization)

WPSO-77 Logviewer not found (BUG)

---

.phan/config.php
ci/phan.sh
ci/phpcs.sh
ci/phplint.sh
composer.json
composer.lock

PHPCS, PHPLint and Phan were misconfigured. This is now fixed. Some work is needed to make them pass.

WPSO-145 Make tests work again

---

README.md
assets/src/js/cloudflare-cache-purge-trigger.js
src/Servebolt/Admin/AdminBarGUI/AdminBarGUI.php
src/Servebolt/Admin/CachePurgeControl/Ajax/PurgeActions.php
src/Servebolt/CachePurge/WordPressCachePurge/WordPressCachePurge.php

Added feature so that terms can also be cache purged from the WP Admin bar, both when in WP Admin and front-end.

WPSO-125 Add "Purge current term cache" in WP Admin bar dropdown

---

src/Servebolt/CachePurge/CachePurge.php

Fixed issue regarding default cache purge driver not being selected whenever driver was not set in options table

WPSO-186 Driver not falling back to default driver when driver not set in options table

---

src/Servebolt/CachePurge/WpObjectCachePurgeActions/ContentChangeTrigger.php

We're were using the action "post_updated" for automatic cache purge of posts. Switched to use action "save_post".

WPSO-211 Switch from "post_updated" to "save_post" for automatic post cache purge

---

src/Servebolt/Compatibility/WpRocket/DisableWpRocketCache.php

Compat: WP Rocket - cache not being properly cleared on sites with multiple domains whenever FPC/ACD is enabled

WPSO-223 Compat: WP Rocket - cache not being properly cleared on sites with multiple domains

---

src/Servebolt/Admin/Assets.php

- Removed the priority-arguments for asset enqueueing

WPSO-265 Change the priority from 100 to default 10 for WP admin assets inclusion

---

composer.json
src/Servebolt/Admin/Assets.php

Fixed composer dependecy issues for packages autoloaded through the 'files'-property in composer.json, corrected typo in comment

WPSO-266 Single-file based composer packages not included in autoloader due to Mozart namespace prefixing

---

src/Servebolt/Admin/Assets.php
src/Servebolt/Admin/CachePurgeControl/CachePurgeControl.php
src/Servebolt/Admin/FullPageCacheControl/FullPageCacheControl.php
src/Servebolt/Admin/PerformanceChecks/PerformanceChecks.php
src/Servebolt/Helpers/Helpers.php

Remove usage of `filemtime` for static assets and replace it by the plugin version (which should be a great cache buster for end-users), since that makes little sense (maybe only for development) so this save a few syscalls.
And also cache the `get_plugin_data()['Version']` result so that multiple calls to the function only parse the plugin data once per request, this is because `get_plugin_data` is quite the beast of a call to do "a lot" now the plugin version number can be used for... cache busting for example 😉

Replace filemtime for static assets

---

src/Servebolt/CachePurge/WpObjectCachePurgeActions/WpObjectCachePurgeActions.php
src/Servebolt/ServeboltOptimizer.php

Made sure that cache purge event listeners also ran when using CLI or Cron, so that we can purge cache for future posts that are being published via the Cron.

Scheduled posts don't trigger cache purging

---

README.md
Readme.txt
src/Servebolt/Compatibility/WpRocket/DisableWpRocketCache.php

Added support for older versions of WP Rocket in compatibility class for cache disabling

WPSO-272 Fatal error - SBO 3.0.1 - wp servebolt fpc activate

---

src/Servebolt/AcceleratedDomains/ImageResize/ImageResize.php
tests/Unit/AcceleratedDomainsImageResize/AcceleratedDomainsImageResizeTest.php

- Omitted image quality parameter if value is default (85)
- Updated tests

WPSO-297 Prevent default image quality parameter from being sent unless it has a different value

---

src/Servebolt/AcceleratedDomains/ImageResize/WpImageSizeIndex.php
src/Servebolt/Helpers/Helpers.php

Added feature to limit sizes in the srcset-attribute based on the sizes-attribute value

WPSO-298 Prevent larger sizes than the max-size to be set in a srcset tag

---

src/Servebolt/Prefetching/ManifestHeaders.php
tests/Unit/Prefetch/ManifestFileWriterTest.php

Changed so that manifest files are printed to individuall headers instead of one + added manifest header test

WPSO-316 Print a header record for each manifest file

---

src/Servebolt/CachePurge/CachePurge.php
src/Servebolt/CachePurge/PurgeObject/ObjectTypes/Post.php
src/Servebolt/CachePurge/WordPressCachePurge/PostMethods.php
src/Servebolt/CachePurge/WordPressCachePurge/SharedMethods.php
src/Servebolt/CachePurge/WordPressCachePurge/TermMethods.php
src/Servebolt/CachePurge/WordPressCachePurge/WordPressCachePurge.php
src/Servebolt/CachePurge/WpCachePurge.php
src/Servebolt/CachePurge/WpObjectCachePurgeActions/ContentChangeTrigger.php
src/Servebolt/CachePurge/WpObjectCachePurgeActions/DeletionCacheTrigger.php
src/Servebolt/CachePurge/WpObjectCachePurgeActions/SlugChangeTrigger.php
src/Servebolt/CachePurge/WpObjectCachePurgeActions/WpObjectCachePurgeActions.php
src/Servebolt/FullPageCache/FullPageCache.php
src/Servebolt/FullPageCache/FullPageCacheSettings.php
src/Servebolt/Helpers/Helpers.php
src/Servebolt/WpCron/Events/MinuteEvent.php
tests/Unit/CachePurgeTriggerTest.php
tests/Unit/FullPageCacheTest.php
tests/Unit/HelpersTest.php
tests/Unit/PurgeUrlsCountConstraintTest.php
tests/Unit/Traits/CachePurgeTestTrait.php
tests/Unit/UrlQueueTest.php

- Moved function 'getFiltersForHook' to to helper file + added test
- Created cache purge test trait for shared methods when testing the cache purge feature
- Fixed issue with test 'testThatPostGetsCachePurgedWhenAddedToFpcExclusion'
- Added tests for automatic cache purge trigger
- Added feature to bypass cache purge queue using static method 'skipQueue' and 'skipQueueOnce'
- Added helper function 'getTaxonomyFromTermId' and implemented it in 'getTaxonomySingularName' + added tests
- Made automatic cache purge events into a 'reloadable' structure
- Fixed potential bug in cache purge feature related to the filter 'sb_optimizer_purge_by_post_original_url'
- Added cache purge actions 'sb_optimizer_purged_term_cache' and 'sb_optimizer_purged_post_cache'

WPSO-231 Whenever a post/term gets deleted we need to purge cache

---

src/Servebolt/Compatibility/Compatibility.php
src/Servebolt/Compatibility/Jetpack/DisableSiteAcceleratorOnAcd.php
src/Servebolt/Compatibility/Jetpack/Jetpack.php
src/Servebolt/Helpers/Helpers.php

Added compat-feature to disabled Jetpack Site Accelerator (formerly Photon CDN) whenever ACD or ACD Image Resizing is active

WPSO-323 Compat: Force disable Jetpack Site Accelerator when Accelerated Domains is active

---

src/Servebolt/AcceleratedDomains/ImageResize/ImageResize.php

Removed type declaration for filter 'wp_get_attachment_image_src' and switched to type casting instead to handle incorrect setups where attachment IDs are specified as strings

WPSO-360 Image Resize alterSingleImageUrl bug

---

src/Servebolt/PluginActiveStateHandling/PluginActiveStateHandling.php
src/Servebolt/WpDatabaseMigrations.php

Fixed issue with database migration runner so that it also runs in other contexts, like the CLI, so that it also runs whenever we activate/deactivate the plugin in CLI-context

WPSO-408 SBO 3.2 - taxonomy and deactivate plugin bug

---

src/Servebolt/Admin/CachePurgeControl/CachePurgeControl.php
src/Servebolt/CachePurge/WordPressCachePurge/WordPressCachePurge.php
src/Servebolt/Queue/Queues/UrlQueue.php
src/Servebolt/Queue/Queues/WpObjectQueue.php

- Minor cleanup
- Added so that the cache purge queue gets cleared every time we switch the cache purge driver (because we could end up with items in the queue that originates from a different drivers with different cache purge methods available)

WPSO-499 Clear cache purge table when driver is changed

---

src/Servebolt/AcceleratedDomains/Prefetching/ManifestFileWriter.php
src/Servebolt/AcceleratedDomains/Prefetching/Prefetching.php

Removed timestamp from manifest filename (due to issues with cached headers that specify the manifest file URLs resulting in 404's for the Cloudflare Prefetch-agent)

WPSO-502 Prefetching not working

---

uninstall.php

Ensure required constants are still present even during plugin uninstallation

WPSO-541 PHP warning on uninstalling Servebolt Optimizer 3.5.3

---

README.md
Readme.txt
languages/servebolt-optimizer.pot
package.json
src/Servebolt/Admin/CachePurgeControl/CachePurgeControl.php
src/Servebolt/Admin/ClearSiteDataHeader/ClearSiteDataHeader.php
src/Servebolt/CachePurge/BrowserManagment.php
src/Servebolt/CachePurge/CachePurge.php
src/Servebolt/CachePurge/Drivers/Cloudflare.php
src/Servebolt/CachePurge/WordPressCachePurge/PostMethods.php
src/Servebolt/CacheTags/AddCacheTagsHeaders.php
src/Servebolt/CacheTags/CanUseCacheTags.php
src/Servebolt/Cli/Cache/CacheSettings.php
src/Servebolt/Helpers/Helpers.php
src/Servebolt/Sdk/Cloudflare/ApiMethods/CachePurge.php
src/Servebolt/ServeboltOptimizer.php
src/Servebolt/Utils/DatabaseMigration/Migrations/8_CacheTagsControl.php
src/Servebolt/Views/cache-settings/cache-purge/configuration/cloudflare-configuration.php

Still some work to be done
- Check migration
- Cloudflare is CachePurge default driver. So cache-tags will be used even if Cloudflare is not configured on a fresh install. Because we set CacheTags to be enabled on fresh installs

Cache tags - Cloudflare

---

README.md
Readme.txt
ci/local-build.sh
languages/servebolt-optimizer.pot
servebolt-optimizer.php
src/Servebolt/Admin/ClearSiteDataHeader/ClearSiteDataHeader.php
src/Servebolt/Admin/LogViewer/LogViewer.php
src/Servebolt/CachePurge/BrowserManagment.php
src/Servebolt/MenuOptimizer/MenuOptimizer.php

* Bugfix: clear-site-data header should now always be sent no matter the browser type
* Bugfix: Menu Optimizer - Added a guard so the cache-indicator comment isn’t appended when the cached payload isn’t a plain string or is already serialized, preventing Timber’s unserialize() warning etc.

Clear-Site-Data Optimization & Menu Optimizer Timber compability 
